References to base profiles
fhir-fi/finnish-base-profiles pull request #116
Opened 2023-04-27 13:12 UTC by Marvasuo

2023-04-27 13:15 UTC, mrinnetmaki approved these changes

2023-04-27 13:15 UTC, mrinnetmaki commented on input/fsh/immunization.fsh
> +* manufacturer only Reference(FiBaseOrganization)
Tämä voisi olla ihan perusversiokin?

2023-04-27 13:20 UTC, mrinnetmaki commented on input/fsh/immunization.fsh
> +* manufacturer only Reference(FiBaseOrganization)
Tai ehkä pyritään pitämään Fi Base Organization hyvin laajana ja sallivana ja tehdään erikseen Fi Base Healthcare Organization, joka ehkä rajoittaa tarkemmin joitakin oideja tai määrää y-tunnusta tms.

2023-04-27 13:22 UTC, mrinnetmaki commented
Otetaan myös "tyjhät" profiilit mukaan. Ainakin Observation.

2023-04-27 19:30 UTC, mrinnetmaki requested changes
Added some more targets for constrained references...
Not sure whether that's helpful and whether you were going to do those anyway...

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/observation.fsh
Eikö Observationille myös perusprofiilirajoitus kentille `basedOn`, `partOf`, `subject`, `encounter`, `performer`, `hasMember`, `derivedFrom`?

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/appointment.fsh
Myös `slot`?

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/healthcareService.fsh
`location`, `coverageArea`.

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/medication.fsh
Myös `ingredient.itemReference`?

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/medicationRequest.fsh
Lisäksi `basedOn`?

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/organization.fsh
`partOf`

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/practitioner.fsh
>  * identifier.assigner only Reference(FiBaseOrganization)
Oho! Muissa ei olla menty sille tasolle, että Identifieriäkin rajoitettaisiin...

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/practitionerRole.fsh
`practitioner`, `organization`, `location`, `healthcareService`

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/schedule.fsh
`actor`

2023-04-27 19:30 UTC, mrinnetmaki commented on input/fsh/slot.fsh
`schedule`

2023-04-28 06:46 UTC, Marvasuo commented on input/fsh/practitioner.fsh
>  * identifier.assigner only Reference(FiBaseOrganization)
Ihan hyvä bongaus. Ajattelin asiaa vain niiden laajennosten näkökulmasta mutta nehän eivät ole velvoittavia. Voi siis olla muitakin arvoja identifierissa kuin mitä laajennoksissa on määritelty. Otetaan tämä pois.

2023-04-28 14:25 UTC, mrinnetmaki approved these changes
Good stuff!

2023-04-28 14:46 UTC, merged