Reduce ipa dependencies
fhir-fi/finnish-base-profiles pull request #138
Opened 2023-06-26 20:41 UTC by mrinnetmaki

2023-06-29 13:18 UTC, mikajylha commented on input/fsh/practitioner.fsh
> -* id 1..1
👍

2023-08-07 06:58 UTC, mikajylha requested changes
Patient medication request refers wrong resource in Scope and usage.

2023-08-07 06:58 UTC, mikajylha commented on input/pagecontent/StructureDefinition-fi-base-patient-medication-request-intro.md
> +The FI Base MedicationRequest derives from the MedicationRequest profile of the International
FI Base Patient MedicationRequest

2023-08-10 12:38 UTC, teropekkola commented on input/pagecontent/StructureDefinition-fi-base-patient-medication-request-intro.md
> +The FI Base MedicationRequest derives from the MedicationRequest profile of the International
Fixed in branch "descriptions" (QA fine tunings).

2023-08-10 13:10 UTC, merged