Provenance agent entity
fhir-fi/finnish-base-profiles pull request #166
Opened 2023-08-30 17:45 UTC by mrinnetmaki

A proposal for the information custodian, expressed in both Provenance.who and Provenance.what.

2023-08-31 17:39 UTC, mrinnetmaki commented
@mikajylha, ready for final review.

2023-09-01 07:57 UTC, mikajylha requested changes
One error that would need to be fixed. One small term issue.

Good work!

I see following issues with this:

entity.what is slightly mis-using indetifier type, to point to a code. Alternative would require use of extensions. Trade-off between a slight mis-use and another extension is reasonably balanced here.

The definition of the code system _KanTa-palvelut - Potilasasiakirjan rekisteritunnus_ is  document-based and doesnt seem to be a perfect fit for entity.what. However the contents of the codesystem fit well.

2023-09-01 07:57 UTC, mikajylha commented on input/pagecontent/StructureDefinition-fi-base-information-custodian-intro.md
> +(*rekisterinpitäjä*), also known as the data processor or register keeper.
About terms, not a big issue.

If I think  _data processor_ in the sense of GDPR I get a bit lost. Isn't custodian more related to data controller (see [this EU article](https://commission.europa.eu/law/law-topic/data-protection/reform/rules-business-and-organisations/obligations/controllerprocessor/what-data-controller-or-data-processor_en)). 

Should the term _data processor_ be completely removed from this page to avoid confusion?

2023-09-01 07:57 UTC, mikajylha commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
This is incorrect. Custodians are not in [SOTE organisaatiorekisteri](https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=421&versionKey=501), they are in [eArkisto - Rekisterinpitäjärekisteri](https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=419&versionKey=496)

Examples need to be updated also.

(THL Codeserver has organization registries for different purposes, at least SOTE-Organisaatio, Rekisterinpitäjä and Apteekki).

2023-09-01 10:18 UTC, mrinnetmaki commented on input/pagecontent/StructureDefinition-fi-base-information-custodian-intro.md
> +(*rekisterinpitäjä*), also known as the data processor or register keeper.
I meant to write Data Controller. OK if I fix that?

2023-09-01 10:39 UTC, mrinnetmaki commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
Argh!

Any idea whether the example should use `1.2.246.10.32213086.19.2` *[Pirkanmaan hyvinvointialueen arkistonmuodostaja](https://koodistopalvelu.kanta.fi/codeserver/pages/codelist-hierarchy-page.xhtml?conceptCodeKey=200063048&versionKey=496&conceptCodeId=1.2.246.10.32213086.19.2#)* or `1.2.246.10.32213086.19.0` *[Pirkanmaan hyvinvointialueen rekisterinpitäjä](https://koodistopalvelu.kanta.fi/codeserver/pages/codelist-hierarchy-page.xhtml?conceptCodeKey=200063048&versionKey=496&conceptCodeId=1.2.246.10.32213086.19.2#)*?

https://koodistopalvelu.kanta.fi/codeserver/pages/codelist-hierarchy-page.xhtml?conceptCodeKey=200063048&versionKey=496&conceptCodeId=1.2.246.10.32213086.19.2

2023-09-01 10:42 UTC, mrinnetmaki commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
@mikajylha [eArkisto - Rekisterinpitäjärekisteri](https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=419&versionKey=496) seems to only include public sector organizations. How should the identifier system be expressed for the private organization?

2023-09-01 10:56 UTC, mrinnetmaki commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
> Julkiset toimijat löytyvät eArkisto-Rekisterinpitäjärekisteristä. Yksityisten toimijoiden tietoja ei viedä lainkaan rekisterinpitäjärekisteriin. Rekisterinpitäjätietona  käytetään yksityisten toimijoiden osalta palvelunantajatietoa (SOTE-organisaatiorekisterin Sektori 2 Yksityinen palvelunantaja, Sektori 3 Yksityinen itse ilmoitettu yksikkö tai koodiston Terveydenhuollon itsenäiset ammatinharjoittajat toimija). SOTE-organisaatiorekisterin osalta saa rekisterinpitäjänä käyttää vain terveydenhuollon toimintayksikköä.

Pitääkö siis tehdä kaksi vaihtoehtoa, julkisille toimijoille `system` olisi tuo rekisterinpitäjärekisteri ja yksityisille  sote-organisaatiorekisteri?

2023-09-01 10:57 UTC, mrinnetmaki commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
Itse asiassa kolme, mukaan myös 1.2.246.537.6.203, Valvira - Terveydenhuollon itsenäiset ammatinharjoittajat

2023-09-01 10:58 UTC, mikajylha commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
>Any idea whether the example should use 1.2.246.10.32213086.19.2 [Pirkanmaan hyvinvointialueen arkistonmuodostaja](https://koodistopalvelu.kanta.fi/codeserver/pages/codelist-hierarchy-page.xhtml?conceptCodeKey=200063048&versionKey=496&conceptCodeId=1.2.246.10.32213086.19.2#) or 1.2.246.10.32213086.19.0 [Pirkanmaan hyvinvointialueen rekisterinpitäjä](https://koodistopalvelu.kanta.fi/codeserver/pages/codelist-hierarchy-page.xhtml?conceptCodeKey=200063048&versionKey=496&conceptCodeId=1.2.246.10.32213086.19.2#)?

Examples should point to_Rekisterinpitäjä_, thats most definitely the right one. (I dont understand the concept of _Arkistonmuodostaja_, its removed from kanta spec too (see 2.2.21.1	ClinicalDocument.participant  – arkistonmuodostaja  for "proof" that its no longer in use. It may have other purposes, but there shouldn't be any need for it in FHIR...). But I don't think we need to explicitly limit this to a specific hiearchy level...

2023-09-01 12:01 UTC, mikajylha commented on input/fsh/informationCustodian.fsh
> +* agent[custodian].who.identifier.system = "urn:oid:1.2.246.537.6.202"
> Pitääkö siis tehdä kaksi vaihtoehtoa, julkisille toimijoille system olisi tuo rekisterinpitäjärekisteri ja yksityisille sote-organisaatiorekisteri?

Kyllä.

> Itse asiassa kolme, mukaan myös 1.2.246.537.6.203, Valvira - Terveydenhuollon itsenäiset ammatinharjoittajat
En löydä tätä CDA Header dokkarista. @mikatuomainen Osaatko kommentoida voiko tätä käyttää rekisterinpitäjänä?

2023-09-01 13:46 UTC, mikajylha commented
1.2.246.537.6.203 was new information for me. Using it seems consistent, even if its missing from Kanta CDA Header spec.

2023-09-01 13:46 UTC, mikajylha approved these changes

2023-09-02 21:25 UTC, mrinnetmaki commented
@mikajylha I did find the code set 1.2.246.537.6.203 through the CDA Header spec, in a way.

> 2.2.17	ClinicalDocument.custodian – asiakirjan rekisterinpitäjä 
> Rekisterinpidosta vastaavan rekisterinpitäjän OID-koodi ja nimi. 
> 
> Julkiset toimijat löytyvät eArkisto-Rekisterinpitäjärekisteristä. Yksityisten toimijoiden tietoja ei viedä lainkaan rekisterinpitäjärekisteriin. Rekisterinpitäjätietona  käytetään yksityisten toimijoiden osalta palvelunantajatietoa (SOTE-organisaatiorekisterin Sektori 2 Yksityinen palvelunantaja, Sektori 3 Yksityinen itse ilmoitettu yksikkö tai **koodiston Terveydenhuollon itsenäiset ammatinharjoittajat toimija**). SOTE-organisaatiorekisterin osalta saa rekisterinpitäjänä käyttää vain terveydenhuollon toimintayksikköä.

2023-09-02 21:26 UTC, merged