Description for Procedure
fhir-fi/finnish-base-profiles pull request #36
Opened 2023-01-25 08:54 UTC by Marvasuo

2023-01-25 10:23 UTC, mrinnetmaki requested changes
At least fix the "videly" typo.

An example would be nice to have. For instance, the use of a robot, showing the `.partOf` structure. A simpler example would be nice too.

2023-01-25 10:23 UTC, mrinnetmaki commented on input/pagecontent/StructureDefinition-fi-base-procedure-intro.md
> +> NOTE: While writing this profile SNOMED code system is not videly used in Finland since adopting the code system started only few years ago and the translation process is still in progess. Neverthe
videly => widely...

Also, I had a bit different wording (and also perhaps a different recommendation) in https://fhir.fi/finnish-base-profiles/terminology.html#snomed-ct.

2023-01-25 10:23 UTC, mrinnetmaki commented on input/pagecontent/StructureDefinition-fi-base-procedure-intro.md
> +> NOTE: While writing this profile SNOMED code system is not videly used in Finland since adopting the code system started only few years ago and the translation process is still in progess. Neverthe
Also, there are specific classes you can use to make notes like this pop out.

I used the `<blockquote class="stu-note">` in https://github.com/fhir-fi/finnish-base-profiles/blob/main/input/pagecontent/index.md, for instance. Pops out, as you can see at https://fhir.fi/finnish-base-profiles/.

Should we use that or another class here?

2023-01-25 10:38 UTC, mrinnetmaki commented
@Marvasuo, you suggest using [AR/YDIN - Toimenpiteen tyyppi](https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=763&versionKey=903) codes in `Procedure.category`. Can you refer to a doc where this is recommended as a practice? Does CGI do this internally?

2023-01-25 10:41 UTC, mrinnetmaki commented
> @Marvasuo, you suggest using [AR/YDIN - Toimenpiteen tyyppi](https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=763&versionKey=903) codes in `Procedure.category`. Can you refer to a doc where this is recommended as a practice? Does CGI do this internally?

The problem for me is that `.category` has a max cardinality of 1, and therefore the category should be really carefully considered.

And the base FHIR spec proposes categories to be drawn from a SNOMED value set http://hl7.org/fhir/valueset-procedure-category.html. This is also closer to what I would expect to see in category, rather than the breadth of scope or severity of the procedure.

2023-01-25 10:48 UTC, mrinnetmaki commented
It would be nice to have a formal link to the procedure codes in the Terminologies section.

Koodistopalvelu says:

> Toimenpideluokitus pohjautuu pohjoismaiseen kirurgiseen luokitukseen (NCSP Nordic Classification of Surgical Procedures), joka on julkaistu ensimmäisen kerran v. 1996. NCSP-luokitusta ylläpitää Pohjoismaiden luokituskeskus (NCC) ja sen tekijänoikeudet ovat NOMESKO:lla.

I did not immediately find a link I could consider the "official one". Anyone else?

2023-01-25 10:51 UTC, mrinnetmaki commented
I did find the document https://norden.diva-portal.org/smash/get/diva2:970547/FULLTEXT01.pdf. It refers to http://www.nordclass.org. However, that page redirects to https://www.ehelse.no/kodeverk/the-nordic-who-fic-classification-centre-nordclass that gives me HTTP 404...

2023-01-25 10:53 UTC, mrinnetmaki commented
It also refers to nom-nos.dk. And that redirects to https://nhwstat.org. That's the right address then, right?

2023-01-30 07:53 UTC, Marvasuo commented on input/pagecontent/StructureDefinition-fi-base-procedure-intro.md
> +> NOTE: While writing this profile SNOMED code system is not videly used in Finland since adopting the code system started only few years ago and the translation process is still in progess. Neverthe
For some reason `blockquote` doesn't understand the link syntax and shows it as plain text. The > blockquote on the other hand works fine.

2023-02-07 13:28 UTC, mrinnetmaki approved these changes
OK for me to pull this in. We can discuss the `.category` later.

2023-02-07 13:28 UTC, mrinnetmaki commented on input/pagecontent/StructureDefinition-fi-base-procedure-intro.md
> +| AR/YDIN - Toimenpiteen tyyppi | 1.2.246.537.6.601 | [https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=763&versionKey=903](https://koodistopalvelu.k
I still don't agree with this being the category. Otherwise good stuff!

2023-02-07 13:52 UTC, closed without merging