Palvelutapahtuma
fhir-fi/finnish-base-profiles pull request #47
Opened 2023-02-02 14:01 UTC by mikajylha

2023-02-10 08:57 UTC, mrinnetmaki requested changes
Can we get polished references with identifiers?

Also, one "MUST not" should be "MUST NOT".

2023-02-10 08:57 UTC, mrinnetmaki commented on input/fsh/examples/encounterPalvelutapahtuma.fsh
> +* serviceProvider.reference = "Organization/1.2.246.10.8286189.10.100012"
I would not mark the reference like this. This indicates that the oid is the `id` of the resource. This results in 
```
"[serviceProvider](http://hl7.org/fhir/R4/encounter.html#Encounter.serviceProvider)" : {
    "[reference](http://hl7.org/fhir/R4/references.html#Reference#Reference.reference)" : "Organization/1.2.246.10.8286189.10.100014"
  },
  ```
  
I would expect the `oid` to be an identifier, and therefore would like to see
```
"serviceProvider" : {
    "type" : "ServiceProvider",
    "identifier": "1.2.246.10.8286189.10.100014"
  },```

All this assuming that the purpose of using the oid here is to indicate that we may actually not have a full FHIR resource available for the organization. Or even if we did and would populate the `.reference` property too, we can add the identifier to communicate the oid.

2023-02-10 08:57 UTC, mrinnetmaki commented on input/fsh/examples/encounterPalvelutapahtuma.fsh
> +* serviceProvider.reference = "Organization/1.2.246.10.8286189.10.100012"
Just a note, we could add the name of the service provider to the reference too.

2023-02-10 08:57 UTC, mrinnetmaki commented on input/pagecontent/StructureDefinition-fi-base-encounter-intro.md
> +Other levels of encounter that are not *palvelutapahtuma*, MUST not contain `use=official` identifier.
with a capital NOT

2023-02-10 15:18 UTC, mikajylha commented on input/pagecontent/StructureDefinition-fi-base-encounter-intro.md
> +context. Laboratory system can resolve Palvelutapahtuma`s OID identifier by fetching the encounter
Fixed

2023-02-10 15:18 UTC, mikajylha commented on input/pagecontent/StructureDefinition-fi-base-encounter-intro.md
> +Other levels of encounter that are not *palvelutapahtuma*, MUST not contain `use=official` identifier.
fixed

2023-02-10 15:19 UTC, mikajylha commented on input/fsh/examples/encounterPalvelutapahtuma.fsh
> +* serviceProvider.reference = "Organization/1.2.246.10.8286189.10.100012"
Uses identifiers now

2023-02-12 12:34 UTC, mrinnetmaki approved these changes
I changed the case of `reference.type`s and changed the first example to use such a format for the reference too. OK?

2023-02-13 06:51 UTC, merged